### ISSUE TITLE
Enh: expose trace format model

### ISSUE THREAD

**Issue by rbtcollins** [andjo403/rs_tracing#4]
It might be nice to expose the trace format model for other crates to use.

For instance, I have a cross-thread tracing problem that rs_tracing is not suitable for yet (at least, as far as I can tell - I have to try it out still :) - I'll be super happy to be wrong) - and having the model would let me write my own hacky data generator , or equally if I want to  process traces in rust.

**Comment by andjo403** [comment]
I'm not sure what "model" is in this context can you give some more info?

**Comment by mineo** [comment]
I think what @rbtcollins is/was referring to is having https://github.com/andjo403/rs_tracing/blob/9bedbdc86494a371fa0355ea4c441a740ebb99c6/src/lib.rs#L307-L377 (the `EventType` and `TraceEvent` types and their serializers) available for use by other crates and not in an `internal` module. At least that's what my use case would be and why I was looking at the `rs_tracing` crate :-)

**Comment by rbtcollins** [comment]
yup, just that, sorry for not replying for so long.

**Comment by andjo403** [comment]
I do not think I'm interested in maintaining that kind of crate it is only 70 lines of code (sure there is more events types that can be implemented and support decode) but this is enough for this crate. It also feels like a lot of work to get the API correct e.g. all data is not valid for all types of events. 
but if someone wants to take that code and make a new crate go ahead :)
